name: BlueGreenDeploymentWithECS CodeDeploy CD Workflow

#Events
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: bgd-dpl
  PROJECT_ENV: dev                
  DOCKER_BUILD_DIR: ./
  DOCKER_FILE: Dockerfile

#Jobs
jobs:
  blue_green_deploy:
    runs-on: ubuntu-latest
    steps:
      #====================================#
      # Checkout repository into runner
      #====================================#
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: infra  # the branch that contains the Terraform code

      #====================================#
      # Configure AWS credentials
      #====================================#
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      #====================================#
      # Checkout repository into runner
      #====================================#
      - name: ECS task deployment using CodeDeploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        env:
          ACTIONS_STEP_DEBUG: true #enable step debug logging
        with:
          task-definition: task-definition.json
          service: example_codedeploy_ecs_svc
          cluster: example_codedeploy_ecs_cluster
          wait-for-service-stability: true
          codedeploy-appspec: appspec.json
          codedeploy-application: example_codedeploy_ecs_app
          codedeploy-deployment-group: example_codedeploy_ecs_dg